# Generated by Django 6.0.3 on 2026-03-31 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Dokumen')),
                ('kategori', models.CharField(choices=[('Surat Masuk', 'Surat Masuk'), ('Surat Keluar', 'Surat Keluar'), ('Proposal', 'Proposal'), ('LPJ', 'Laporan Pertanggungjawaban'), ('Lainnya', 'Dokumen Lainnya')], max_length=50)),
                ('file_dokumen', models.FileField(upload_to='dokumen/%Y/%m/')),
                ('keterangan', models.TextField(blank=True, help_text='Catatan tambahan (opsional)', null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('pengunggah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
